// Custom shader file for tremor.bsp
// Generated by Q3Map2 (ydnar)
// Do not edit! This file is overwritten on recompiles.

tremor/E64035C3EC6CDA53F9B6843E8B1DCF74
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}

	{
		map textures/tremor/vented_5
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/C5A9DFE9CF2CBC0935BF59AA7DD247C0
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.57812 0.00000
	}

	{
		map textures/tremor/vented_1
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/B73286DD85372432B4875FBB15915429
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.11719 0.00000
	}

	{
		map textures/tremor/vented_1
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/8100A89CC10C76C45878A433D4FBDE4B
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.31250 0.03125
	}

	{
		map textures/tremor/vented_1
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/B6E312F539BA78F2F0EC0503C85511EE
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3map2_tremor/lm_0000
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
	}

	{
		map textures/tremor/grate3
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/D8A2D713AC51B108C553A535F1045562
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3map2_tremor/lm_0003
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
	}

	{
		map textures/tremor/grate3
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/6BECD3B2569973B25DCEF634EC6AD040
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3map2_tremor/lm_0004
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
	}

	{
		map textures/tremor/grate3
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/3874D7AE45C5A01E9D83A68F1230FEEB
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3map2_tremor/lm_0004
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/tremor/grate3
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/FD4DCA6D91D9D06458A66BD546160B5B
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}

	{
		map textures/tremor/runner_2
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/B8062F6E414A0DC53C6C9B7DEBED8038
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/tremor/runner_2
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/716C8C0FA4520198133ACAA647DB2A10
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}

	{
		map textures/tremor/vented_2
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/0EE9E2886E209E89ACBFFD96935A09CA
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.38281 0.03906
	}

	{
		map textures/tremor/vented_2
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/604A790EBC3B282088801872D3479415
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.56250 0.03906
	}

	{
		map textures/tremor/vented_2
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/A514AD2196A89454B607A5E6AA2D430C
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.35156 0.07812
	}

	{
		map textures/tremor/vented_2
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/03D200720A5F78E084D09335150EEAFF
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3map2_tremor/lm_0000
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
	}

	{
		map textures/titan/support_3
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/623F539E08968AA4AFD1C549AABC41DD
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3map2_tremor/lm_0000
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
	}

	{
		map textures/titan/dark_metal_2
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/F066C946F78E6914EB17756F2B89C1FF
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.03906 0.00000
	}

	{
		map textures/niveus/metal_panels
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/4F6FEDB29D59D1ED89152DE1C7799EDF
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.84375 0.00781
	}

	{
		map textures/niveus/metal_panels
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/D39F03FF472208079F1A5C6BEBBCC90D
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/q3map2_tremor/lm_0000
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
	}

	{
		map textures/niveus/metal_panels
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

